version: "3"

services:
  db:
    container_name: pg13
    image: timescale/timescaledb:latest-pg13
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-Python123}
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
    volumes:
      - ./db_data/postgres/db-data:/var/lib/postgresql/data/ # persist data even if container shuts down
    ports:
      - 5432:5432

  app:
    container_name: django
    build:
      context: .
      dockerfile: ./Dockerfile
    image: "django-boilerplate:v1"
    env_file:
      - 'src/.env'
    environment:
      - DATABASE_HOST=pg13
      - DATABASE_PORT=5432
    restart: always
    # volumes:
    #   - '$PWD/src:/app'
    command: /gunicorn.sh
    ports:
      - "5001:5000"
